# meta-compulab 

## Supported CompuLab Machines
* cm-fx6-evk
* cl-som-imx6ul
* cl-som-imx7
* cl-som-imx6

## How To

### Prepare BSP Environment

#### Install i.MX NXP BSP repo
* Select an available NXP branch: imx-4.1-krogoth/imx-morty
* Set IMX_BRANCH environment variable.
[source,console]
$: export IMX_BRANCH=imx-4.1-krogoth
or
$: export IMX_BRANCH=imx-morty

WARNING: In order evaluate Yocto Morty follow this instructions: https://github.com/compulab-yokneam/compulab-bsp/tree/morthy 

#### Download Yocto Project NXP Layers:
[source,console]
$: repo init -u git://git.freescale.com/imx/fsl-arm-yocto-bsp.git -b ${IMX_BRANCH}
$: repo sync

#### Clone meta-compulab layer:
[source,console]
$: git clone https://github.com/compulab-yokneam/meta-compulab sources/meta-compulab

### Build Procedure
* Select an available machine: cm-fx6-evk/cl-som-imx6ul/cl-som-imx7/cl-som-imx6
* Set MACHINE environment variable:
[source,console]
$: export MACHINE=cm-fx6-evk
or
$: export MACHINE=cl-som-imx6ul
or
$: export MACHINE=cl-som-imx7
or
$: export MACHINE=cl-som-imx6

* Select an available distro: x11/fb/xwayland/wayland
* Set DISTRO environment variable:
[source,console]
$: export DISTRO=fsl-imx-x11
or
$: export DISTRO=fsl-imx-fb
or
$: export DISTRO=fsl-imx-xwayland
or
$: export DISTRO=fsl-imx-wayland

#### Create Build Environment
[source,console]
$: source fsl-setup-release.sh -b build-${MACHINE}-${DISTRO}

#### Pre-Build Steps
* Add the meta-compulab location to the conf/bblayers.conf

[source,console]
$: [[ -f conf/bblayers.conf ]] && (sed -i '$aBBLAYERS += " ${BSPDIR}/sources/meta-compulab "' conf/bblayers.conf) || echo "Warning: Invalid Build Directory"

WARNING: Stop Here if warning shows up

* Add the second packaging option to the conf/local.conf

[source,console]
$: [[ -f conf/local.conf ]] && sed -i '/PACKAGE_CLASSES/ a PACKAGE_CLASSES += " package_deb"' conf/local.conf || echo "Warning: Invalid Build Directory"

#### Build Instruction
 * Select an available image: fsl-image-gui/fsl-image-qt5/compulab-eval-image/compulab-eval-image-xfce
 * Set IMAGE environment variable:
[source,console]
$: export IMAGE=fsl-image-gui
or
$: export IMAGE=fsl-image-qt5
or
$: export IMAGE=compulab-eval-image
or
$: export IMAGE=compulab-eval-image-xfce

* Image buld command:

 This commad builds entire image.
[source,console]
$: bitbake ${IMAGE}

* Kernel buld command:

 This commad builds CompuLab kernel only.
[source,console]
$: bitbake linux-compulab

* U-Boot buld command:

 This commad builds CompuLab U-Boot only.
[source,console]
$: bitbake u-boot-compulab
