# meta-compulab 

# !!! It is a BETA !!!
WARNING: This is a prelimitary branch that fails with ERROR: imx-gpu-viv-1_5.0.11.p8.7-hfp-r0 do_fetch: Fetcher failure See an nxp thread: https://community.nxp.com/thread/452335
 Using p8.6 does not help. The build fails with:
ERROR: Multiple versions of imx-gpu-viv are due to be built (/.../freescale/yocto/morty/sources/meta-fsl-bsp-release/imx/meta-bsp/recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.2.0.p4-aarch32.bb /.../freescale/yocto/morty/sources/meta-fsl-bsp-release/imx/meta-bsp/recipes-graphics/imx-gpu-viv/imx-gpu-viv_5.0.11.p8.7-hfp.bb). Only one version of a given PN should be built in any given build. You likely need to set PREFERRED_VERSION_imx-gpu-viv to select the correct version or don't depend on multiple versions.
In order evaluate Yocto Morty follow this instructions: https://github.com/compulab-yokneam/compulab-bsp/tree/morthy

## Supported CompuLab Machines
* cm-fx6-evk
* cl-som-imx6ul
* cl-som-imx7
* cl-som-imx6

## How To

### Prepare BSP Environment

#### Install i.MX NXP BSP repo
[source,console]
$: repo init -u git://git.freescale.com/imx/fsl-arm-yocto-bsp.git -b imx-morty

#### Download Yocto Project NXP Layers:
[source,console]
$: repo sync

#### Clone meta-compulab layer:
[source,console]
$: git clone https://github.com/compulab-yokneam/meta-compulab sources/meta-compulab

### Build Procedure
#### Select an available machine: cm-fx6-evk/cl-som-imx6ul/cl-som-imx7/cl-som-imx6
[source,console]
$: export MACHINE=cm-fx6-evk
or
$: export MACHINE=cl-som-imx6ul
or
$: export MACHINE=cl-som-imx7
or
$: export MACHINE=cl-som-imx6

#### Select an available distro: x11/fb/xwayland/wayland
[source,console]
$: export DISTRO=fsl-imx-x11
or
$: export DISTRO=fsl-imx-fb
or
$: export DISTRO=fsl-imx-xwayland
or
$: export DISTRO=fsl-imx-wayland

#### Create Build Environment
[source,console]
$: source fsl-setup-release.sh -b build-${MACHINE}-${DISTRO}

#### Pre-Build Steps
* Add the meta-compulab location to the conf/bblayers.conf

[source,console]
$: [[ -f conf/bblayers.conf ]] && (sed -i '$aBBLAYERS += " ${BSPDIR}/sources/meta-compulab "' conf/bblayers.conf) || echo "Warning: Invalid Build Directory"

WARNING: Stop Here if warning shows up

* Add the second packaging option to the conf/local.conf

[source,console]
$: [[ -f conf/local.conf ]] && sed -i '/PACKAGE_CLASSES/ a PACKAGE_CLASSES += " package_deb"' conf/local.conf || echo "Warning: Invalid Build Directory"

#### Build
##### Image
[source,console]
$: bitbake fsl-image-gui
or
$: bitbake fsl-image-qt5

##### Kernel Only
[source,console]
$: bitbake linux-compulab

##### U-Boot Only
[source,console]
$: bitbake u-boot-compulab
