# Quick Start Guide

## Supported CompuLab Machines

* `cl-som-imx8`
* `ucm-imx8m-mini`

# Prepare NXP BSP
[source,console]
repo init -u git://source.codeaurora.org/external/imx/imx-manifest.git -b imx-linux-sumo -m imx-4.14.98-2.0.0_ga.xml
repo sync

# Set a desire machine
* `cl-som-imx8`
[source,console]
COMPULAB_MACHINE=cl-som-imx8

* `ucm-imx8m-mini`
[source,console]
COMPULAB_MACHINE=ucm-imx8m-mini

# Download CompuLab meta layer
* `cl-som-imx8`
[source,console]
git clone -b master https://github.com/compulab-yokneam/meta-bsp-imx8mq.git sources/meta-bsp-imx8mq/

* `ucm-imx8m-mini`
[source,console]
git clone -b master https://github.com/compulab-yokneam/meta-bsp-imx8mq.git sources/meta-bsp-imx8mm/

# Set up build environment
* `cl-som-imx8`
[source,console]
DEVENV=Yes MACHINE=${COMPULAB_MACHINE} source sources/meta-bsp-imx8mq/tools/setup-imx8mq-env -b build-xwayland

* `ucm-imx8m-mini`
[source,console]
DEVENV=Yes MACHINE=${COMPULAB_MACHINE} source sources/meta-bsp-imx8mm/tools/setup-imx8mm-env -b build-xwayland

# Build SDK 
This example shows how to build the CompuLab Qt5 Build Environment for the `${COMPULAB_MACHINE}`
[source,console]
bitbake -c populate_sdk compulab-qt5-build-env

## How To Install
* As soon as the `bitbake` process has finished with the success, issue this script from the command line as root user:
[source,console]
./tmp/deploy/sdk/fsl-imx-xwayland-glibc-x86_64-compulab-qt5-build-env-aarch64-toolchain-4.14-sumo.sh

* Set the installation path or agree on the default:
[source,console]
MX Release Distro SDK installer version 4.14-sumo
Enter target directory for SDK (default: /opt/fsl-imx-xwayland/4.14-sumo):
You are about to install the SDK to "/opt/fsl-imx-xwayland/4.14-sumo". Proceed[Y/n]? Y

* Wait for the done:
[source,console]
Extracting SDK........................................................................................................................................................................................................................................................................................................................................................................................................................................................................done
Setting it up...done
SDK has been successfully set up and is ready to be used.

* Make use of the build environment:
Each time you wish to use the SDK in a new shell session, you need to source the environment setup script e.g.
[source,console]
. /opt/fsl-imx-xwayland/4.14-sumo/environment-setup-aarch64-poky-linux
