# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory containing .bb and .bbappend files, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "compulab-desktop-main"
BBFILE_PATTERN_compulab-desktop-main := "^${LAYERDIR}/"
BBFILE_PRIORITY_compulab-desktop-main = "4"

LAYERSERIES_COMPAT_compulab-desktop-main = "wrynose walnascar"
