#!/bin/bash

get_cmdline_device() {
root=$(findmnt -o SOURCE -n /)
[[ -b ${root} ]] && block_boot_dev=$(udevadm info -n ${root} | awk -F "block" '(/DEVPATH/)&&(split($2,a,"/"))&&($0="/dev/"a[2])')
}

block_boot_dev=''
WORK=/usr/local/bin/cl-deploy.work

[[ ! -t 0 ]] && EXEC="xterm -e" || EXEC="source"
# Prevent spanning another xterm if we in
[[ ${TERM} = "xterm" ]] && EXEC="source"

get_cmdline_device
export BOOT=${block_boot_dev}
[[ -z ${SRC} && -z ${EMUL} ]] && export SRC=${BOOT}
export SCAN_ALL=0

${EXEC} ${WORK}
