#!/bin/bash

PID_FILE=/var/run/cl-camera.pid
camera_stop() {
    if [[ -f ${PID_FILE} ]];then
        PID=$(cat ${PID_FILE})
        kill -9 ${PID}
        rm -rf ${PID_FILE}
        exit 0
    fi
}

camera_start() {
    if [ -d /sys/class/video4linux/${CAMERA} ];then
        SRC="v4l2src device=/dev/${CAMERA}"
        export TEXT=$( cat /proc/device-tree/product-name; cat <<< " "${CAMERA} )
        OVERP=""
    else
        SRC="videotestsrc"
        export TEXT="Make sure that the camera is connected to the board...."
        OVERP="color=0 valignment=center halignment=left font-desc=Sans,48"
    fi

    camera_start_${MODE}

    PID=$!
    echo ${PID} > ${PID_FILE}
}

camera_start_stream() {
    SINK="waylandsink window-width=1280 window-height=720"
    SINK="autovideosink"
    GST_COMMAND="${GST} ${SRC} ! "video/x-raw,width=1280,height=720,format=${FORMAT}" ! clockoverlay ! textoverlay text=\"${TEXT}\" ! ${SINK}"
cat << eof | tee /tmp/camera_start_stream.cmd > /dev/null
${GST_COMMAND}
eof
    ${GST_COMMAND} &
}

camera_start_image() {
    local image_file="/tmp/singel_image_$(date +%F_%X | sed 's/[-:]//g').jpg"
    ${GST} ${SRC} num-buffers=1 ! "video/x-raw,width=1280,height=720,format=${FORMAT}" ! jpegenc ! filesink location=${image_file}
    ${GST} filesrc location=${image_file} ! jpegdec ! imagefreeze ! autovideosink &
}

camera_get() {
    local _CAMERA=( $(for f in /dev/video*;do [[ $(v4l2-ctl --info --device ${f} | awk '($0 ~ /VIV/ || $0 ~ /mxc-isi-cap/ ) && ($0=$NF)') ]] && echo $(basename ${f}) ; done; cat <<< " fakecamera") )
cat << eof
Available sensors and commands:
------------------------------
eof
    for c in ${!_CAMERA[@]};do
    [[ ${c} -eq ${sensor} ]] && default="*" || default=""
cat << eom
	$c ${_CAMERA[$c]}; sensor=$c cl-camera ${default}
eom
    done
    export CAMERA=${_CAMERA[${sensor}]}
}

camera_main() {
    camera_stop
    camera_get
    CAMERA=${CAMERA} MODE=${MODE} camera_start
}

MODE=${MODE:-stream}
[[ ${MODE} = 'stream' ]] || MODE=image
FORMAT=${FORMAT:-NV12}
sensor=${sensor:-0}
GST="gst-launch-1.0 --no-position"

camera_main
