#!/bin/bash

PID_FILE=/var/run/cl-camera.pid

if [[ -f ${PID_FILE} ]];then
PID=$(cat ${PID_FILE})
kill -9 ${PID}
rm -rf ${PID_FILE}
exit 0
fi

CAMERA=${CAMERA:-video0}

if [ -d /sys/class/video4linux/${CAMERA} ];then
SRC="v4l2src device=/dev/${CAMERA}"
eval $(udevadm info -ap /sys/devices/soc0 | awk '/machine/' | sed 's/ATTR{\(.*\)}/\1/g;s/==/=/g')
export TEXT=${machine}
OVERP=""
else
SRC="videotestsrc"
export TEXT="Make sure that the camera is connected to the board...."
OVERP="color=0 valignment=center halignment=left font-desc=Sans,48"
fi

SINK="waylandsink window-width=1280 window-height=720"
gst-launch-1.0 ${SRC} ! 'video/x-raw,width=1280,height=720,format=NV12' ! textoverlay text="'${TEXT}'" ! ${SINK} &

PID=$!

echo ${PID} > ${PID_FILE}
