SRC_URI_append_cm-fx6 += "file://cm-fx6/defconfig \
	file://cm-fx6/0001-ARM-dts-update-support-for-cm-fx6.patch \
	file://cm-fx6/0002-ARM-i.MX6-cm-fx6-add-cm-fx6-platform-driver.patch \
	file://cm-fx6/0003-ARM-i.MX6-cm-fx6-Add-defconfig.patch \
	file://cm-fx6/0004-ARM-i.MX6-cm-fx6-add-gpc-node.patch \
	file://cm-fx6/0005-ARM-i.MX6-audio-add-analog-audio-support.patch \
	file://cm-fx6/0006-ARM-i.MX6-add-depends-property-to-gpmi-nand.patch \
	file://cm-fx6/0007-ARM-i.MX6-update-defconfig-for-nand.patch \
	file://cm-fx6/0008-ARM-i.MX6-add-mxc_dvi-driver.patch \
	file://cm-fx6/0009-ARM-i.MX6-dts-refactoring-of-the-second-video-output.patch \
	file://cm-fx6/0010-ARM-i.MX6-dts-ldo-hdmi-changes.patch \
	file://cm-fx6/0011-ARM-i.MX6-dts-udshc3-set-polarity-value.patch \
	file://cm-fx6/0012-ARM-i.MX6-dts-sata-refactoring.patch \
	file://cm-fx6/0013-ARM-i.MX6-dts-ldb-refactoring.patch \
	file://cm-fx6/0014-ARM-i.MX6-dts-enable-mipi_dsi.patch \
	file://cm-fx6/0015-ARM-i.MX6-pcie-refactoring.patch \
	file://cm-fx6/0016-ARM-i.MX6-dts-clean-up-unnecesary-code.patch \
	file://cm-fx6/0017-ARM-i.MX6-update-defconfig.patch \
	file://cm-fx6/0018-Bluetooth-btmrvl-disable-SD8787-AMP-device.patch \
	file://cm-fx6/0019-ARM-i.MX6-HDMI-Fix-HDMI-PHY-init-hang.patch \
"
