#!/bin/bash

### BEGIN INIT INFO
# Provides:		bt-start
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	CompuLab empty bt-start
### END INIT INFO

case "$1" in
start)
	;;
stop)
	;;
status)
	;;
*)
cat << eom
	Usage: $0 {start|stop|status}
eom
	exit 1
esac

exit 0
