#!/bin/bash

WORK=/usr/local/bin/cl-uboot.work

[[ -t 0 ]] && EXEC="source" || for T in weston-terminal matchbox-terminal xterm; do
command -v ${T} &>/dev/null
	if [ $? -eq 0 ];then
		export EXEC="${T} -e"
		break
	fi
done

${EXEC} ${WORK}
