#!/bin/bash -xv

WORK=/usr/local/bin/cl-uboot.work

[[ ! -z ${DISPLAY} ]] && EXEC="xterm -e" || EXEC="source"
# Prevent spanning another xterm if we in
[[ ${TERM} = "xterm" ]] && EXEC="source"

${EXEC} ${WORK}
